# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=100)),
                ('CEO_name', models.CharField(max_length=100)),
                ('company_phone', models.CharField(max_length=15)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_location', models.CharField(max_length=200)),
                ('company_country', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('current_project', models.CharField(max_length=80)),
                ('private_report', models.BooleanField()),
                ('files_attached', models.TextField()),
            ],
        ),
    ]
